name: Build testing

on:
  push:
    branch:
      - master

jobs:
  build:
    name: Using ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dockerfile file
      run: |
          docker build -t test:1 .
    - name: docker login
      run: |
        echo ${{ secrets.DOCKER_USERNAME }}
        
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/test_for_cicd
          

      
    
        
